### ISSUE TITLE
Handle initialization errors

### ISSUE THREAD

**Issue by joshrotenberg** [joshrotenberg/lingua_ex#3]
- too few languages 
- out of range mrd

**Comment by joshrotenberg** [comment]
Trying to detect with only one language results in:

```elixir
iex(1)> Lingua.detect("państwowych", builder_option: :with_languages, languages: [:english])
thread '<unnamed>' panicked at 'LanguageDetector needs at least 2 languages to choose from', /Users/joshrotenberg/.cargo/registry/src/github.com-1ecc6299db9ec823/lingua-1.2.0/src/builder.rs:86:13
                                                                               ** (ArgumentError) argument error
    (lingua 0.2.0) Lingua.Nif.detect_language_of("państwowych", :with_languages, [:english], 0.0, false)
iex(1)> 
```

Trying to detect with an out of range minimum relative distance:

```elixir
iex(4)> Lingua.detect("państwowych", builder_option: :with_languages, languages: [:english, :russian], minimum_relative_distance: 1.0)
thread '<unnamed>' panicked at 'minimum relative distance must lie in between 0.0 and 0.99', /Users/joshrotenberg/.cargo/registry/src/github.com-1ecc6299db9ec823/lingua-1.2.0/src/builder.rs:143:13
                                                                                ** (ArgumentError) argument error
    (lingua 0.2.0) Lingua.Nif.detect_language_of("państwowych", :with_languages, [:english, :russian], 1.0, false)
iex(4)> 
```

Ideally, these would return `{:error, :too_few_languages}` and `{:error, :minimum_relative_distance_out_of_range}` or similar.

These should be handled explicitly with `std::panic::catch_unwind`. This probably means breaking up `build_detector` and handling each in isolation. It might also be helpful to handle the common parts of `detect_language_of` and `compute_language_confidence_values` to handle the errors first, and then branch for the two different calls, or just make them one function that if/elses.
